node.default['mysql']['develop_user'] = 'dev_user'
node.default['mysql']['develop_password'] = 'develop_password'
node.default['mysql']['develop_db_name'] = 'development'
node.default['mysql']['user'] = 'vagrant'
node.default['mysql']['group'] = 'vagrant'
node.default['home_path'] = '/home/vagrant'
node.default['ruby_version'] = '2.2.2'
node.default['nginx']['port'] = '80'
